### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#27]
I always get something like this:

`No defintions found for "/tmp/dante-asalewkrjew.hs" ...`

**Comment by jyp** [comment]
Could you please provide a minimal example with code?

**Comment by dalaing** [comment]
I was seeing this as well, for everything from little snippets to my biggest projects.

It has changed since then - first to locking up my emacs to the point of requiring a force kill, and then to doing nothing with the message: "No jump handler was able to find this symbol".

I get the "No definitions found" error if I use `projectile-find-tag`, and everything works fine if I use `find-tag`.

I'm using dante via the haskell spacemacs layer from the develop branch, and these projects are all nix-ified.  They're all configured from within nix-shell, after which I'm running spacemacs from outside of the nix-shell (although it still happens from within the nix-shell).

I figure it might just be the price of being on the develop branch, but I figured I'd provide some info in case any of it is useful.

**Comment by dalaing** [comment]
Also - if I disable dante from spacemacs, the haskell-mode go to definition and `projectile-find-tag` both start working again.  I'll poke around in the spacemacs haskell layer and see what I find, but I don't really know my away around the layer / haskell-mode / elisp at the moment...

**Comment by dalaing** [comment]
Develop branch takes away, and develop branch giveth: I just did an update and things are working again, for the first time in quite a while.  It seems that I can actually have it all after all :)
