### ISSUE TITLE
GHC 8.2.2 and the newest -Wmissing-home-modules

### ISSUE THREAD

**Issue by michalrus** [jyp/dante#60]
Hello!

We’re using `-Werror -Wall` for compilation and, on 8.2.2, when loading (`:l`) a file from `/tmp/`, which Dante does, the following happens:

```
λ> :l /tmp/blah1234.hs

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:

[ … a list of all modules in the project … ]

<no location info>: error: 
Failing due to -Werror.
Failed, no modules loaded.
(0.05 secs,)
λ> 
```

----

An (ugly?) workaround is to add `-Wwarn=missing-home-modules` in the Cabal file, e.g.:

```
library
  ghc-options:         -Wall -Werror -Wwarn=missing-home-modules [ … other options … ]
```

This way, the `missing-home-modules` stays a warning in spite of `-Werror`, and Dante is usable. 

Another option would be to use `-Wno-missing-home-modules`, to make GHCi less chatty (without `-Wno-…`, for each reload it dumps the whole module list, but as a warning).

**Comment by michalrus** [comment]
Some context: https://www.reddit.com/r/haskell/comments/7a9d8b/why_is_cabal_so_bad_at_managing_modules/dp8tv3z/

**Comment by jyp** [comment]
You can now customize `dante-load-flags`. Should we have `-Wwarn=missing-home-modules` in there?

**Comment by michalrus** [comment]
P-p-perhaps, if this is the correct way around this.

**Comment by jyp** [comment]
It seems like the warning does not really hurt. Without more info I'd leave the users to customize this themselves. (Note -Wall is now disabled by default.)

**Comment by shajra** [comment]
Does Dante have a good way of only adding flags for certain versions of GHC?  This flag/warning is new for 8.2, so I'd imagine using the flag for prior versions would error out the ghci invocation.

Otherwise, if I understand the situation correctly, this warning will be tripped every time because of the nature of how Dante loads Haskell snippets in the REPL instance.  So it makes sense to me to put in `-Wwarn=missing-home-modules` as a default flag.

**Comment by jyp** [comment]
AFAIU GHC simply ignores the warning flags that it does not understand. So I'll just activate the flag.
